services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clademusic-web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Mount SSL certificates (create these directories first)
      - ./ssl:/etc/nginx/ssl:ro
      # Optional: custom nginx config override
      # - ./nginx.custom.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DOMAIN=${DOMAIN:-localhost}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 3s
      start_period: 10s
      retries: 3
    networks:
      - clademusic-network

networks:
  clademusic-network:
    driver: bridge
